export const LAB_MODULES = [
  {
    id: "module-1",
    order: 1,
    title: "Computers, Programs, and the Web",
    promise: "Explore browsers, servers, web languages, program flow, files, and paths.",
    status: "available",
  },
  {
    id: "module-2",
    order: 2,
    title: "HTML",
    promise: "Build the meaningful structure of the expense tracker.",
    status: "available",
  },
  {
    id: "module-3",
    order: 3,
    title: "CSS",
    promise: "Design the tracker and make it adapt across screens.",
    status: "available",
  },
  {
    id: "module-4",
    order: 4,
    title: "JavaScript Foundations",
    promise: "Understand values, memory, functions, conditions, and arrays.",
    status: "next",
  },
  {
    id: "module-5",
    order: 5,
    title: "JavaScript in the Browser",
    promise: "Connect code to the DOM and build the working vanilla tracker.",
    status: "planned",
  },
  {
    id: "module-6",
    order: 6,
    title: "TypeScript",
    promise: "Make the project’s data and expectations explicit.",
    status: "planned",
  },
  {
    id: "module-7",
    order: 7,
    title: "Why React Exists",
    promise: "Experience the coordination problem React was designed to solve.",
    status: "planned",
  },
  {
    id: "module-8",
    order: 8,
    title: "Interactive React",
    promise: "Build forms, state, events, and reliable interface behavior.",
    status: "planned",
  },
  {
    id: "module-9",
    order: 9,
    title: "Real Application Data",
    promise: "Manage identity, derived values, data flow, and edge cases.",
    status: "planned",
  },
  {
    id: "module-10",
    order: 10,
    title: "Persistence, Quality, and Deployment",
    promise: "Save, debug, test, move, deploy, and explain the finished project.",
    status: "planned",
  },
] as const;
